// Downloads the classic 90-level Sokoban set (50 "Original" + 40 "Extra")
// from the public-domain xsokoban distribution and packs it into js/levels.js.
//
// Usage:  node tools/fetch-levels.mjs
//
// Level layouts are by Thinking Rabbit (Hiroyuki Imabayashi, 1982-84) and are
// distributed here as they have been in xsokoban since 1989. See README.md.

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const BASE = 'https://raw.githubusercontent.com/andrewcmyers/xsokoban/master/screens/screen.';
const COUNT = 90;

const here = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(here, '..', 'js', 'levels.js');

async function fetchScreen(n) {
  const res = await fetch(BASE + n);
  if (!res.ok) throw new Error(`screen.${n}: HTTP ${res.status}`);
  const text = await res.text();
  // Normalise: strip trailing whitespace per line, drop blank lines at the ends.
  const lines = text.replace(/\r/g, '').split('\n').map(l => l.replace(/\s+$/, ''));
  while (lines.length && lines[0] === '') lines.shift();
  while (lines.length && lines[lines.length - 1] === '') lines.pop();
  return lines.join('\n');
}

const levels = [];
for (let n = 1; n <= COUNT; n++) {
  process.stdout.write(`\rFetching screen ${n}/${COUNT}...`);
  levels.push(await fetchScreen(n));
}
process.stdout.write('\n');

const sets = [
  {
    id: 'original',
    name: 'Original & Extra',
    author: 'Thinking Rabbit',
    description: 'The 50 original levels (1982-84) plus the 40 "Extra" levels, as shipped with xsokoban.',
    groups: [{ name: 'Original', count: 50 }, { name: 'Extra', count: 40 }],
    levels,
  },
];

const banner =
  '// Generated by tools/fetch-levels.mjs - do not edit by hand.\n' +
  '// Level layouts (c) Thinking Rabbit; distributed as in the public-domain xsokoban package.\n';
mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, banner + 'window.SOKOBAN_LEVEL_SETS = ' + JSON.stringify(sets, null, 1) + ';\n');
console.log(`Wrote ${levels.length} levels to ${outFile}`);
